### ISSUE TITLE
SchemaTestCase: `KeyError: 0`  occurs on objects with `array`,`O2M`, `M2M`

### ISSUE THREAD

**Issue by paolopaolopaolo** [yeti/YAK-server#19]
@rmutter, @baylee, Here is the error log I get when I run `assertSchemaGet` on an object with a nested Schema:

```
Traceback (most recent call last):
  File "/vagrant/wheres_yeti/feed/tests/test_endpoints.py", line 17, in test_list_endpoint
    response = self.assertSchemaGet(url, None, "$pictureResponse", self.user1)
  File "/home/vagrant/wheres_yeti/src/yak-server-master/yak/rest_core/test.py", line 247, in assertSchemaGet
    self.check_response_data(response, response_object_name)
  File "/home/vagrant/wheres_yeti/src/yak-server-master/yak/rest_core/test.py", line 229, in check_response_data
    self.check_schema_keys(results_data, self.schema_objects[response_object_name])
  File "/home/vagrant/wheres_yeti/src/yak-server-master/yak/rest_core/test.py", line 187, in check_schema_keys
    new_data_object = new_data_object[0]
KeyError: 0
```

I think the recent change where we turned "objects" in the schema file into an Object (when it was an array previously) is causing this error. For my purposes, I'm just going to hold off on using O2M, array, or M2M as values in the schema.

**Comment by baylee** [comment]
I think you should just fix the test to work with new signals

**Comment by rmutter** [comment]
@baylee you already implemented the new schema structure into the tests in YAK-server so unsure where this error is coming from for @paolopaolopaolo
